### ISSUE TITLE
missing includes on Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by waldemarKunkel** [bbqsrc/cargo-ndk#173]
I developed my application on Manjaro and had no problems there, but when it came to building it on Jenkins on Ubuntu 24.04 LTS, that's when disaster struck.
Now I've set up a VM and am trying to solve the problem locally. 

<details><summary>build.rs</summary>
<p>

```rust

let bindings = bindgen::Builder::default()
    .header(
        crate_dir
            .join("import/include/corporate.h")
            .into_os_string()
            .into_string()
            .expect("Failed to load header"),
    )
    .generate()?;
let out_path = PathBuf::from(std::env::var("OUT_DIR")?);
bindings.write_to_file(out_path.join("corporate.rs"))?;

``` 

</p>
</details> 

<details><summary>cargo ndk --bindgen -t armeabi-v7a -o ./jniLibs build -vv</summary>
<p>

```shell

    Detected NDK v26.2.11394342 (/usr/lib/android-ndk) [ANDROID_NDK_HOME]
   Exporting CARGO_NDK_CMAKE_TOOLCHAIN_PATH="/usr/lib/android-ndk/build/cmake/android.toolchain.cmake"
   Exporting CARGO_NDK_OUTPUT_PATH="./jniLibs"
     Setting Android SDK platform level to 21
    Building targets (armeabi-v7a)
    Building armeabi-v7a (armv7-linux-androideabi)
   Exporting CARGO_NDK_ANDROID_TARGET="armeabi-v7a"
   Exporting AR_armv7-linux-androideabi="/usr/lib/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
   Exporting BINDGEN_EXTRA_CLANG_ARGS_armv7_linux_androideabi="--sysroot=/usr/lib/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot -I/usr/lib/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/arm-linux-androideabi"
   Exporting CARGO_NDK_SYSROOT_LIBS_PATH="/usr/lib/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi"
   Exporting CARGO_NDK_SYSROOT_PATH="/usr/lib/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
   Exporting CARGO_NDK_SYSROOT_TARGET="arm-linux-androideabi"
   Exporting CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_AR="/usr/lib/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
   Exporting CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER="/home/waldemar/.cargo/bin/cargo-ndk"
   Exporting CC_armv7-linux-androideabi="/usr/lib/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"
   Exporting CFLAGS_armv7-linux-androideabi="--target=armv7a-linux-androideabi21"
   Exporting CXXFLAGS_armv7-linux-androideabi="--target=armv7a-linux-androideabi21"
   Exporting CXX_armv7-linux-androideabi="/usr/lib/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++"
   Exporting RANLIB_armv7-linux-androideabi="/usr/lib/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib"
   Exporting _CARGO_NDK_LINK_CLANG="/usr/lib/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"
   Exporting _CARGO_NDK_LINK_TARGET="--target=armv7a-linux-androideabi21"
    Invoking cargo (/home/waldemar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo) with args: ["build", "-vv"]
       Fresh glob v0.3.2
       Fresh unicode-ident v1.0.18
       Fresh proc-macro2 v1.0.95
       Fresh quote v1.0.40
       Fresh minimal-lexical v0.2.1
       Fresh regex-syntax v0.8.5
       Fresh memchr v2.7.5
       Fresh cfg-if v1.0.1
       Fresh syn v2.0.104
       Fresh regex-automata v0.4.9
       Fresh nom v7.1.3
       Fresh libloading v0.8.8
       Fresh libc v0.2.174
       Fresh either v1.15.0
       Fresh itertools v0.13.0
       Fresh clang-sys v1.8.1
       Fresh prettyplease v0.2.36
       Fresh cexpr v0.6.0
       Fresh regex v1.11.1
       Fresh bitflags v2.9.1
       Fresh rustc-hash v2.1.1
       Fresh log v0.4.27
       Fresh shlex v1.3.0
       Fresh bindgen v0.72.0
warning: unused import: `process::Command`
 --> build.rs:1:31
  |
1 | use std::{env, path::PathBuf, process::Command};
  |                               ^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `hello_android` (build script) generated 1 warning
   Compiling hello_android v0.1.0 (/home/waldemar/workspace/hello_android)
     Running `CARGO=/home/waldemar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo CARGO_CFG_FEATURE='' CARGO_CFG_PANIC=unwind CARGO_CFG_TARGET_ABI=eabi CARGO_CFG_TARGET_ARCH=arm CARGO_CFG_TARGET_ENDIAN=little CARGO_CFG_TARGET_ENV='' CARGO_CFG_TARGET_FAMILY=unix CARGO_CFG_TARGET_HAS_ATOMIC=16,32,64,8,ptr CARGO_CFG_TARGET_OS=android CARGO_CFG_TARGET_POINTER_WIDTH=32 CARGO_CFG_TARGET_VENDOR=unknown CARGO_CFG_UNIX='' CARGO_ENCODED_RUSTFLAGS='' CARGO_MANIFEST_DIR=/home/waldemar/workspace/hello_android CARGO_MANIFEST_PATH=/home/waldemar/workspace/hello_android/Cargo.toml CARGO_PKG_AUTHORS='' CARGO_PKG_DESCRIPTION='' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE='' CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=hello_android CARGO_PKG_README='' CARGO_PKG_REPOSITORY='' CARGO_PKG_RUST_VERSION='' CARGO_PKG_VERSION=0.1.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE='' DEBUG=true HOST=x86_64-unknown-linux-gnu LD_LIBRARY_PATH='/home/waldemar/workspace/hello_android/target/debug/deps:/home/waldemar/workspace/hello_android/target/debug:/home/waldemar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib:/home/waldemar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib' NUM_JOBS=4 OPT_LEVEL=0 OUT_DIR=/home/waldemar/workspace/hello_android/target/armv7-linux-androideabi/debug/build/hello_android-176027e826090eac/out PROFILE=debug RUSTC=/home/waldemar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc RUSTC_LINKER=/home/waldemar/.cargo/bin/cargo-ndk RUSTDOC=/home/waldemar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustdoc TARGET=armv7-linux-androideabi /home/waldemar/workspace/hello_android/target/debug/build/hello_android-126023127de825a1/build-script-build`
[hello_android 0.1.0] cargo:rustc-link-lib=c++_shared
[hello_android 0.1.0] cargo::rustc-link-search=/home/waldemar/workspace/hello_android/import/android/lib/armeabi-v7a
[hello_android 0.1.0] cargo::rustc-link-lib=corporatelib
[hello_android 0.1.0] /usr/lib/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/stdint.h:33:10: fatal error: 'stddef.h' file not found
[hello_android 0.1.0] Error: ClangDiagnostic("/usr/lib/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/stdint.h:33:10: fatal error: 'stddef.h' file not found\n")
error: failed to run custom build command for `hello_android v0.1.0 (/home/waldemar/workspace/hello_android)`

Caused by:
  process didn't exit successfully: `CARGO=/home/waldemar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo CARGO_CFG_FEATURE='' CARGO_CFG_PANIC=unwind CARGO_CFG_TARGET_ABI=eabi CARGO_CFG_TARGET_ARCH=arm CARGO_CFG_TARGET_ENDIAN=little CARGO_CFG_TARGET_ENV='' CARGO_CFG_TARGET_FAMILY=unix CARGO_CFG_TARGET_HAS_ATOMIC=16,32,64,8,ptr CARGO_CFG_TARGET_OS=android CARGO_CFG_TARGET_POINTER_WIDTH=32 CARGO_CFG_TARGET_VENDOR=unknown CARGO_CFG_UNIX='' CARGO_ENCODED_RUSTFLAGS='' CARGO_MANIFEST_DIR=/home/waldemar/workspace/hello_android CARGO_MANIFEST_PATH=/home/waldemar/workspace/hello_android/Cargo.toml CARGO_PKG_AUTHORS='' CARGO_PKG_DESCRIPTION='' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE='' CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=hello_android CARGO_PKG_README='' CARGO_PKG_REPOSITORY='' CARGO_PKG_RUST_VERSION='' CARGO_PKG_VERSION=0.1.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE='' DEBUG=true HOST=x86_64-unknown-linux-gnu LD_LIBRARY_PATH='/home/waldemar/workspace/hello_android/target/debug/deps:/home/waldemar/workspace/hello_android/target/debug:/home/waldemar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib:/home/waldemar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib' NUM_JOBS=4 OPT_LEVEL=0 OUT_DIR=/home/waldemar/workspace/hello_android/target/armv7-linux-androideabi/debug/build/hello_android-176027e826090eac/out PROFILE=debug RUSTC=/home/waldemar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc RUSTC_LINKER=/home/waldemar/.cargo/bin/cargo-ndk RUSTDOC=/home/waldemar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustdoc TARGET=armv7-linux-androideabi /home/waldemar/workspace/hello_android/target/debug/build/hello_android-126023127de825a1/build-script-build` (exit status: 1)
  --- stdout
  cargo:rustc-link-lib=c++_shared
  cargo::rustc-link-search=/home/waldemar/workspace/hello_android/import/android/lib/armeabi-v7a
  cargo::rustc-link-lib=corporatelib

  --- stderr
  /usr/lib/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/stdint.h:33:10: fatal error: 'stddef.h' file not found
  Error: ClangDiagnostic("/usr/lib/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/stdint.h:33:10: fatal error: 'stddef.h' file not found\n")

``` 

</p>
</details> 

I've already searched other issues and tried to set different environment variables but nothing helps. 
What am I missing?

**Comment by bbqsrc** [comment]
Hi @waldemarKunkel, can you try using the `feature/bindgen` branch?

```
cargo install --git https://github.com/bbqsrc/cargo-ndk --branch feature/bindgen
```

**Comment by waldemarKunkel** [comment]
Hi @bbqsrc, thanks for the quick response. Now it works, great! 
I also tried to build the example before and after. Didn't work with 3.5.4 but works with this branch. 
Are you going to create a release with these changes anytime soon?
Is there anything I could help with?
